openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: lesson2
servers:
  - url: /v1
paths:
  /accounts/{id}:
    get:
      description: Get Balance
      operationId: Accounts/getBalance
      parameters: 
      - in : path
        name: id
        required: true
        schema:
          type : integer
      responses:
        '200':
          description: empty response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /accounts:
    post:
      description: Create Account
      operationId: Accounts/createAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    get:
      description: Query Accounts
      operationId: Accounts/getAccounts
      parameters:
      - in : query
        name: customerId
        schema:
          type: integer
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      type: object
      properties:
        balance:
          type: integer
        id:
          type: integer
        label:
          type: string
        type:
          type: string
          enum:
            - checking
            - savings